language: php

php:
  - 5.6
  - 7.0
  - 7.2

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

sudo: false

before_script:
  # https://github.com/symfony/symfony/issues/4687
  - composer update --dev --no-interaction --prefer-source $PREFER_LOWEST

script:
  - php vendor/bin/phpunit tests/